haumea/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework.authtoken.views import obtain_auth_token


# admin.site.index_template = 'admin/haumea_index.html'
# admin.site.site_header = '买卖通'

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += [
    url(r'^store/', include('store.urls.web')),
    url(r'^goods/', include('scrapy.urls.web')),
]

urlpatterns += [
    url(r'^api/auth/', include('rest_framework.urls',
                           namespace='rest_framework')),
    url(r'^api/get-token/', obtain_auth_token),
    url(r'^api/scrapy/', include('scrapy.urls.api')),
    url(r'^api/', include('store.urls.api')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

store/models.py
from datetime import datetime, timedelta
from django.core import urlresolvers
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django_pandas.managers import DataFrameManager


class Shop(models.Model):
    (tmall, taobao, jd) = range(3)
    SHOP_TYPE_CHOICES = [
        (tmall, _('tmall')),
        (taobao, _('taobao')),
        (jd, _('jd'))
    ]

    # slug = fields.RandomCharField(length=12, include_alpha=False, editable=False, db_index=True)
    name = models.CharField(unique=True, max_length=128, blank=True,)
    brief = models.TextField(blank=True, null=True)
    type = models.SmallIntegerField(_('type'), default=tmall, choices=SHOP_TYPE_CHOICES)
    shop_url = models.CharField(unique=True, max_length=255, blank=True)
    status = models.BooleanField(default=True)
    created_datetime = models.DateTimeField(default=timezone.now, db_index=True)

    class Meta:
        verbose_name = '商店'
        verbose_name_plural = '商店'

    def __str__(self):
        return "{}".format(self.name)

    def get_absolute_url(self):
        return urlresolvers.reverse('store-detail-view', args=[self.pk, ])

    @property
    def goods_count(self):
        return self.entry.count()


class Entry(models.Model):
    shop = models.ForeignKey(Shop,
                             related_name='entry',
                             on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    brief = models.TextField(default='')
    url = models.URLField(max_length=255, null=True, unique=True)
    datetime_created = models.DateTimeField(default=timezone.now, db_index=True)

    objects = DataFrameManager()

    class Meta:
        verbose_name = "商品"
        verbose_name_plural = "商品"

    def __str__(self):
        return "{}".format(self.name)

    @property
    def image_url(self):
        _image_url = self.images.first()
        return _image_url

    @property
    def latest_price(self):
        _price = 0.
        try:
            _price = self.stat.last().price
        except Exception as e:
            pass
        return _price

    @property
    def latest_sale_num(self):
        _sale_num = 0
        try:
            _sale_num = self.stat.last().sale_num
        except Exception as e:
            pass
        return _sale_num

    @property
    def latest_update_date(self):
        date = datetime.now()
        try:
            date = self.stat.last().date_created
        except Exception as e:
            pass
        return date

    @property
    def month_average_price(self):
        end_date = datetime.now()
        start_date = end_date - timedelta(days=30)
        qs = self.stat.filter(date_created__range=(start_date, end_date))
        df = qs.to_dataframe(index='date_created')
        return round(df.price.mean(), 2)

    @property
    def month_average_sale_revenue(self):
        end_date = datetime.now()
        start_date = end_date - timedelta(days=30)
        qs = self.stat.filter(date_created__range=(start_date, end_date))
        df = qs.to_dataframe(index='date_created')
        price_se = df.price.convert_objects(convert_numeric=True)
        sale_se = df.sale_num.diff().fillna(0)
        return round(price_se.mul(sale_se).mean(), 2)

    @property
    def sales_volume_month(self):
        end_date = datetime.now()
        start_date = end_date - timedelta(days=30)
        qs = self.stat.filter(date_created__range=(start_date, end_date))
        df = qs.to_dataframe(index='date_created')
        return df.sale_num.diff().fillna(0).sum()

    @property
    def sales_revenue_month(self):
        end_date = datetime.now()
        start_date = end_date - timedelta(days=30)
        qs = self.stat.filter(date_created__range=(start_date, end_date))
        df = qs.to_dataframe(index='date_created')
        price_se = df.price.convert_objects(convert_numeric=True)
        sale_se = df.sale_num.diff().fillna(0)
        return round(price_se.mul(sale_se).sum(), 2)

    def get_absolute_url(self):
        return urlresolvers.reverse('entry-detail-view', args=[self.pk, ])


class EntryStat(models.Model):
    entry = models.ForeignKey(Entry, related_name='stat')
    price = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    sale_num = models.IntegerField(default=0)
    date_created = models.DateField(default=timezone.now, db_index=True)

    objects = DataFrameManager()

    class Meta:
        ordering = ['date_created']

    def __str__(self):
        return '{price} - {sale_num} - {date}'.format(
            price=self.price,
            sale_num=self.sale_num,
            date=self.date_created
        )


class EntryImage(models.Model):
    entry = models.ForeignKey(Entry,
                              related_name='images',
                              on_delete=models.CASCADE)
    image = models.URLField(max_length=255, editable=False)

    def __str__(self):
        return self.image

store/views/api.py
from rest_framework import generics
from rest_framework.pagination import PageNumberPagination

from store.models import Shop, Entry
from store.serializers import ShopSerializer, EntrySerializer


class StandardResultsSetPagination(PageNumberPagination):
    page_size = 10
    page_size_query_param = 'size'
    max_page_size = 1000


class ShopListView(generics.ListCreateAPIView):
    queryset = Shop.objects.all()
    serializer_class = ShopSerializer
    pagination_class = StandardResultsSetPagination

    def perform_create(self, serializer):
        serializer.save()


class ShopDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Shop.objects.all()
    serializer_class = ShopSerializer


class EntryListView(generics.ListCreateAPIView):
    queryset = Entry.objects.all()
    serializer_class = EntrySerializer

    def perform_create(self, serializer):
        serializer.save()


class EntryDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Entry.objects.all()
    serializer_class = EntrySerializer

store/views/web.py
import pygal
from pygal import Config
from django.views.generic import ListView, DetailView
from django.utils.log import getLogger

from store.models import Shop, Entry
from datetime import datetime, timedelta


logger = getLogger('django')


class StoreListView(ListView):
    model = Shop
    queryset = Shop.objects.all()
    template_name = 'store/list.html'
    paginate_by = 20


class StoreDetailView(ListView):
    model = Entry
    template_name = 'store/detail.html'
    paginate_by = 20

    def get_queryset(self):
        self.queryset = Entry.objects.filter(shop_id=self.store_id)
        return self.queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        store = Shop.objects.get(pk = self.store_id)
        context.update({
            'store': store,
        })
        return context

    def get(self, request, *args, **kwargs):
        self.store_id = kwargs.pop('pk')
        return super().get(request, *args, **kwargs)


class EntryView(DetailView):
    model = Entry
    template_name = 'entry/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        end_date = datetime.now()
        start_date = end_date - timedelta(days=30)
        stat = self.object.stat.filter(date_created__range=(start_date, end_date))
        df = stat.to_dataframe(index='date_created')
        context.update({
            'sale_chart': self.get_sale_chart(stat, df=df),
            'price_chart': self.get_price_chart(stat),
        })

        return context

    def get_sale_chart(self, stat, df):
        config = Config()
        config.show_legend = False
        config.human_readable = True
        # config.fill = True
        config.x_label_rotation = 90
        config.pretty_print = True
        config.min_scale = 12
        config.height = 480
        # config.print_values = True
        # config.print_values_position = 'top'
        # config.value_font_size=30

        sale_chart = pygal.Line(config)
        sale_chart.title = '销量与销售额'
        sale_chart.x_labels =  map(lambda x: x.date_created.strftime("%Y-%m-%d"), stat)
        price_se = df.price.convert_objects(convert_numeric=True)
        sale_se = df.sale_num.diff().fillna(0)
        sale_chart.add('销量', [row for row in sale_se])
        sale_chart.add('销售额', [row for row in price_se.mul(sale_se)], secondary=True)
        # return sale_chart.render()
        return sale_chart.render_data_uri()

    def get_price_chart(self, stat):
        config = Config()
        config.show_legend = False
        config.human_readable = True
        config.x_label_rotation = 90
        config.pretty_print = True
        config.min_scale = 12
        config.height = 480

        price_chart = pygal.Line(config)
        price_chart.title = '售价走势图'
        price_chart.x_labels = map(lambda x: x.date_created.strftime("%Y-%m-%d"), stat)
        price_chart.add('价格', [row.price for row in stat])
        return price_chart.render_data_uri()

templates/store/detail.html
{% extends 'base/base.html' %}
{% load i18n %}
{% load bootstrap3 %}

{% block container %}
    <div class="container">
        <div class="row">
            <h1>{{ store }}</h1>
        </div>
        <div class="row table-responsive">
            <table class="table table-condensed table-bordered">
                <thead>
                    <tr>
{#                        <th>#</th>#}
                        <th>{% trans 'image' %}</th>
                        <th>{% trans 'name' %}</th>
                        <th>{% trans 'average price in 30 day' %}</th>
                        <th>{% trans 'average sale revenue in 30 day' %}</th>
                        <th>{% trans 'sale volume' %}</th>
                        <th>{% trans 'sales revenue' %}</th>
{#                        <th>{% trans 'price' %}</th>#}
{#                        <th>{% trans 'sale-num' %}</th>#}
                        <th>{% trans 'latest-update-date' %}</th>
                        <th>{% trans 'opearation' %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for row in object_list %}
                        <tr>
{#                            <td>{{ row.id }}</td>#}
                            <td><img class="img-responsive" width="60"  src="{{ row.image_url }}"></td>
                            <td>{{ row.name }}</td>
                            <td>{{ row.month_average_price }}</td>
                            <td>{{ row.month_average_sale_revenue }}</td>
                            <td>{{ row.sales_volume_month }}</td>
                            <td>{{ row.sales_revenue_month }}</td>
{#                            <td>{{ row.latest_price }}</td>#}
{#                            <td>{{ row.latest_sale_num }}</td>#}
                            <td>{{ row.latest_update_date }}</td>
                            <td>
                                <div class="btn-group">
                                    <a class="btn btn-info" target="_blank" href="{{ row.get_absolute_url }}">详情</a>
                                    <a class="btn btn-default" target="_blank" href="{{ row.url }}">商品链接</a>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="row">
            <div class="col-sm-12">
                {% bootstrap_pagination page_obj extra=request.GET.urlencode size="large" %}
            </div>
        </div>
    </div>
{% endblock %}

templates/store/list.html
{% extends 'base/base.html' %}
{% load i18n %}
{% load bootstrap3 %}


{% block container %}
    <div class="container">
        <div class="row">
            <div class="table-responsive">
            <table class="table table-condensed table-bordered">
                <thead>
                    <tr>
{#                        <th>#</th>#}
                        <th>{% trans 'store name' %}</th>
                        <th>{% trans 'store type' %}</th>
                        <th>{% trans 'monitor store goods' %}</th>
                        <th>{% trans 'opearation' %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for row in object_list %}
                    <tr>
{#                        <td>{{ row.pk }}</td>#}
                        <td>
                            <a target="_blank" href="{{ row.get_absolute_url }}">{{ row.name }}</a>
                        </td>
                        <td>{{ row.get_type_display }}</td>
                        <td>{{ row.goods_count }}</td>
                        <td><a href="{{ row.shop_url }}" target="_blank">去店铺</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                {% bootstrap_pagination page_obj extra=request.GET.urlencode size="large" %}
            </div>
        </div>
    </div>
{% endblock %}